FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the service files
COPY . .

# Expose the service's port
EXPOSE 8003

# Command to start the Django server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8003"]
